name: Chessed
version: $version
main: com.jakubmeysner.chessed.Chessed
api-version: 1.19

commands:
  play:
    description: Invites a player to a game.
    permission: chessed.play
    usage: /play <player> [rapid|blitz] [random|white|black]

  invite:
    description: Controls invites.
    permission: chessed.play
    usage: |
      /invite (accept|decline|cancel) ...
      /invite accept <player>
      /invite decline <player>
      /invite cancel

  game:
    description: Controls games.
    permission: chessed.play
    usage: |
      /game (draw|resign) ...
      /game draw offer
      /game draw accept
      /game draw decline
      /game resign

  arena:
    description: Controls arenas.
    permission: chessed.arena
    usage: |
      /arena (add|build|remove) ...
      /arena add <arena> [<worldName>] [<x>] [<y>] [<z>] [<yaw>]
      /arena build <arena>
      /arena remove <arena>

permissions:
  chessed.*:
    default: op
    children:
      chessed.play: true
      chessed.arena: true
  chessed.play:
    default: true
  chessed.arena:
    default: op
